#pragma once

#define APOLLO_MOUSE_BUTTON_LEFT     1
#define APOLLO_MOUSE_BUTTON_MIDDLE   2
#define APOLLO_MOUSE_BUTTON_RIGHT    3
#define APOLLO_MOUSE_BUTTON_X1       4
#define APOLLO_MOUSE_BUTTON_X2       5

#define APOLLO_MOUSE_BUTTON_MASK(X)  (1u << ((X)-1))
#define APOLLO_MOUSE_BUTTON_LMASK    APOLLO_MOUSE_BUTTON_MASK(APOLLO_MOUSE_BUTTON_LEFT)
#define APOLLO_MOUSE_BUTTON_MMASK    APOLLO_MOUSE_BUTTON_MASK(APOLLO_MOUSE_BUTTON_MIDDLE)
#define APOLLO_MOUSE_BUTTON_RMASK    APOLLO_MOUSE_BUTTON_MASK(APOLLO_MOUSE_BUTTON_RIGHT)
#define APOLLO_MOUSE_BUTTON_X1MASK   APOLLO_MOUSE_BUTTON_MASK(APOLLO_MOUSE_BUTTON_X1)
#define APOLLO_MOUSE_BUTTON_X2MASK   APOLLO_MOUSE_BUTTON_MASK(APOLLO_MOUSE_BUTTON_X2)
